// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using server.Data;

#nullable disable

namespace server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("shared.RefreshTokenRecords", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AccessTokenJTI")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAtUTC")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpireAtUTC")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ReplacedByRefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("RevokedAtUTC")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAtUTC")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("AccessTokenJTI");

                    b.HasIndex("RefreshToken");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokenRecords");
                });

            modelBuilder.Entity("shared.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAtUTC")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Role")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUTC")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Avatar = "",
                            CreatedAtUTC = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "trunghau@mstsoftware.vn",
                            IsEmailVerified = true,
                            Name = "Mai Trung Hau",
                            Password = "$2a$11$hujKbVuakeRCRTpkQOgFOuW7XucJlZIBk1KWXhVP7Vct0E3C44vDi",
                            Phone = "",
                            Role = 2,
                            Status = 1,
                            UpdatedAtUTC = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Avatar = "",
                            CreatedAtUTC = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "john@example.com",
                            IsEmailVerified = true,
                            Name = "John Doe",
                            Password = "$2a$11$yDt/GUmudcv29HAmrnBKyOzvNXnTmlwvOaMCpwh8t3/wTmk1b331u",
                            Phone = "",
                            Role = 0,
                            Status = 1,
                            UpdatedAtUTC = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Avatar = "",
                            CreatedAtUTC = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "jane@example.com",
                            IsEmailVerified = true,
                            Name = "Jane Smith",
                            Password = "$2a$11$4gEnSkWwdsI/.5baZtkShOfHNoc3LEsxm8uwBVcmGSzMHGhVj8opm",
                            Phone = "",
                            Role = 1,
                            Status = 1,
                            UpdatedAtUTC = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Avatar = "",
                            CreatedAtUTC = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "bob@example.com",
                            IsEmailVerified = false,
                            Name = "Bob Johnson",
                            Password = "$2a$11$6jC9r6N1lnzvlQtswvZIT.yiGxwsNPRypqFhGJV5Y5.bTxO8scTh6",
                            Phone = "",
                            Role = 0,
                            Status = 0,
                            UpdatedAtUTC = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Avatar = "",
                            CreatedAtUTC = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "alice@example.com",
                            IsEmailVerified = true,
                            Name = "Alice Williams",
                            Password = "$2a$11$b479NmPvRLL1wjNy87QR8eO5262EZk6nUi4GEpjQLuYeWZAlaBYRa",
                            Phone = "",
                            Role = 0,
                            Status = 2,
                            UpdatedAtUTC = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("shared.RefreshTokenRecords", b =>
                {
                    b.HasOne("shared.User", "User")
                        .WithMany("RefreshTokenRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("shared.User", b =>
                {
                    b.Navigation("RefreshTokenRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
